AcgApp/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib import admin
# from .views import contact,imbuto,imishwi,ifumbire,contact_us

urlpatterns = [
    url(r'^imbuto', views.imbuto, name='imbuto'),
    url(r'^imishwi', views.imishwi, name='imishwi'),
    url(r'^ifumbire', views.ifumbire, name='ifumbire'),
    url(r'^contact',views.contact, name='contact'),
    url(r'^contact_us', views.contact_us, name='contact_us')
      
]

acg/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
  
   
]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),  # NOQA
    url(r'^AcgApp/', include('AcgApp.urls')),
    url(r'^', include('cms.urls')),
    url(r'^', include('djangocms_forms.urls')),
   
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

AcgApp/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class ContactTable(models.Model):
    firstname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message=models.TextField()

AcgApp/forms.py
from django import forms
from django.conf import settings
from .models import ContactTable
from django.forms import ModelForm


class ContactForm(forms.ModelForm):
    firstname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=True)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}),required=True)
    message = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),required=True)
    class Meta:
        model = ContactTable
        fields = ('firstname','email','message')

AcgApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import ContactTable
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from .forms import ContactForm
from django.core.mail import send_mail
import logging


# Create your views here.
def imbuto(request):
    return render(request, '../../acg/templates/imbuto.html', {'imbuto': imbuto})

def imishwi(request):
    return render(request, '../../acg/templates/imishwi.html',{'imishwi': imishwi})

def ifumbire(request):
    return render(request, '../../acg/templates/ifumbire.html',{'ifumbire': ifumbire})

def contact(request):
    return render(request, '../../acg/templates/contact.html',{'contact':contact})

# # def contact(request):
#     return render(request, '../../acg/templates/contact.html',{'contact':contact})  
def contact_us(request):
    if request.method == 'POST':
        if request.POST.get('firstname') and request.POST.get('email') and request.POST.get('message'):
            post = ContactForm()
            post.firstname = request.POST.get('firstname')
            post.email = request.POST.get('email')
            post.message = request.POST.get('message')
            post.save()

            return render(request, '../../acg/templates/contact.html',{'contact':post})

        else:
            return render(request, '../../acg/templates/contact.html',{'contact':post})
        
#         # create a form instance and populate it with data from the request:
#         form = ContactForm(request.POST)
#         # check whether it's valid:
#         if form.is_valid():
#                 form.firstname = form.cleaned_data['first_name']
#                 form.email = form.cleaned_data['email']
#                 form.message = form.cleaned_data['message']
#                 form.save()
                            
               
#                 # redirect to accounts page:
#                 return HttpResponseRedirect('../../acg/templates/contact.html')

#    # No post data availabe, let's just show the page.
#     else:
#         form = ContactForm()

#     return render(request, '../../acg/templates/contact.html', {'form': form})


    # form= ContactForm(request.POST or None)
    # if form.is_valid():
    #     firstname= form.cleaned_data.get("firstname")
    #     email= form.cleaned_data.get("email")
    #     message=form.cleaned_data.get("message")

    #     # if request.user.is_authenticated():
    #     #     subject= str(request.user) + "'s Comment"
    #     # else:
    #     #     subject= "A Visitor's Comment"

    #     # message= firstname + " with the email, " + email + ", sent the following message:\n\n" + message
    #     # send_mail(subject, message, 'dlhylton@gmail.com', [email])

    #     context= {'form': form}
    #     return render(request, '../../acg/templates/contact.html', context)

    # else:
    #     context= {'form': form}
    #     return render(request, '../../acg/templates/contact.html', context)

AcgApp/templates/AcgApp/contact_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Forms Tutorial</title>
</head>
<body>
<h2>Django Forms Tutorial</h2>

<form action="/thankyou/" method="post">
    {% csrf_token %}
    <table>
    {{form.as_table}}

 </table>
<input type="submit" value="Submit" />
</form>
</body>
</html>

acg/templates/about.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
{% placeholder content or %} 
<div class="container-fluid">

</div>
{% endplaceholder %}
{% endblock content %}

<footer>
    {% include "footer_word.html" %} 
</footer>

acg/templates/base-init.html
{% load cms_tags menu_tags sekizai_tags %}
<!doctype html>
<html>
    <head>
        <title>{% block title %}This is my new project home page{% endblock title %}</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <style type="text/css">
        *{
            margin: 0;
            padding: 0;
            }
        .nav-bar {
	        position: sticky;
	        top: 0;
	        z-index: 10;
            }
            .nav {
                padding-left: 0;
               
            }
            .navbar-nav{
                background-color: blueviolet;
            }
            .nav li {
                display: inline;
                list-style-type: none;
                padding-right: 20px;
                color: white;
            }
            .container {
                width: 940px;
                margin: 0 auto
            }
            .content {
                float: left;
                width: 80%;
            }
            .sidebar {
                float: left;
                width: 20%;
            }
            .style-slide-blue{
            width: 100%;
            height: 20%;
            }
        </style>
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        <div class="container">
            <ul class="nav">
                {% show_menu 0 100 100 100 %}
            </ul>
            {% block content %}{% endblock content %}
        </div>
        {% render_block "js" %}
    </body>
</html>

acg/templates/base.html
{% load i18n cms_tags menu_tags sekizai_tags %}
<!DOCTYPE html>
<html lang="{{LANGUAGE_CODE}}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>DjangoCmsCode</title>

    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css'
        integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/acg/css.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% render_block "css" %}

    <head>
        <title>{% block title %}This is my new project home page{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <style type="text/css">
            #nav-bar {
                position: sticky;
                top: 0;
                z-index: 10;
            }

            .navbar-brand img {
                width: 100px;
                height: 37px;
                border-radius: 10px;
            }

            .fa-bars {
                color: #fff;
                font-size: 30px !important;
            }

            .navbar {
                background: rgb(130, 148, 241);
                /* margin-top: 420px; */

            }

            .carsousel {
                margin-top: 15px;
            }

            .ul {
                list-style-type: none;
                margin: 5px;
                padding: 0;
                overflow: hidden;
                background-color: #333;
                margin-left: 50px;
                width: 80px;
            }

            .nav-bar {
                background: cornflowerblue;
            }

            .navbar-nav li {
                padding: 0 10px;
            }

            .navbar-nav li a {
                color: rgb(19, 18, 18) !important;
                font-weight: 600;
            }

            .nav li {
                display: block;
                list-style-type: none;
                padding-right: 20px;
                text-decoration-line: none;
                color: black;
            }

            .navbar-nav li {
                padding: 0 10px;
            }

            .nav-item a {
                color: black;
            }

            .nav li a {
                display: block;
                color: #333;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
                width: 80px;
                margin-left: 20px;
            }

            .ul li a:hover {
                background-color: rgba(87, 66, 66, 5.096);
                width: 115px;
            }

            .loremcontainer {
                width: 100%;
                height: 30%;
                background-color: cadetblue;
                color: black;
            }

            .arcword {
                padding: 70px;
            }

            .content {
                float: left;
                width: 80%;
            }

            .sidebar {
                float: left;
                width: 20%;
            }

            .btn-dark {
                color: white;
                text-decoration: none;
                background-color: #333;
            }

            .buttongetstarted {
                margin-left: 750px;
                color: white;
                text-decoration: none;
                background-color: #333;
                height: 150px;
                width: 170px;
            }

            .startpage {
                color: white;
            }

            .alertsecond {
                width: 100%;
            }

            .alert-arrow-down {
                width: 100%;
            }

            .quotes {
                width: 100%;
                background-color: #333;
                color: white;
                height: 200px;
            }

            .nav-link {
                color: #333;
            }

            .fa-facebook {
                padding: 5px;
                left: 45%;
                text-align: center;
            }

            .fa-instagram {
                padding: 5px;
            }

            .fa-twitter {
                padding: 5px;
            }

            .fa-linkedin {
                padding: 5px;
            }

            .third-style {
                width: 100%;
                margin-left: 0px;
            }

            style-icon {
                line-height: 100px;
                vertical-align: middle
            }

            .rowsize {
                margin: 0px;
                padding: 50px;
                margin-top: -20px;
                width: 100%;
            }

            .iconsheep {
                margin-left: 70px;
            }

            .alert-icon {
                margin-top: -9px;
            }

            .carsousel {
                margin-top: 10px;
                background: cornflowerblue;
                width: 100%;
            }

            .row-slide {
                background-color: rgb(11, 11, 133);
                width: 100%;
                height: 40%;

            }

            .contact-form {
                margin-top: 150px;
                box-shadow: 2px 0px 50px 2px #888888;
                text-align: center;
                text-emphasis: size;
                background-color: #b3bbb302;
                color:rgb(49, 36, 36);
            }
            .text-center {
                margin-top: 10px;
            }

            .services {
                margin-top: -17px;
            }

            .row-background {
                background-color: #b3bbb302;
                width: 100%;
                box-shadow: 10px 10px 8px 10px #888888;

            }

            .services-backround {
                background-color: #abadab28;
                padding:20px;
                width: 100%;
                
            } 
            .project-vision-mission{
                box-shadow: 10px 10px 8px #888888;
            }

            .about_image-height {
                height: 250px;
                width: 90%;
                margin-top: 100px;
                box-shadow: 20px 20px 10px #888888;
                /* margin-left: 20px; */
            }
            .awasome{
                margin-top: 5%;
                margin-bottom: 7%;
               
                height: 50%;
                padding-top: 30px;
                
            }

            .footerblue {

                width: 100%;
                margin-top: -10px;
                background-color: #011A98;
                color: white;
            }

            .formcontact {
                margin-top: 400px;
            }

            .clasformstyle {
                margin-top: 50px;
            }

            .top-space {
                background-color: #799038;
            }

            .size-imbuto {
                background-color: #799038;
                width: 200px;
                height: 50px;
            }

            .product-name {
              
               margin-top:150px; 
               
                margin-left: 50px;
            }

            .imbito1 {
                border-radius: 50%;

                background-color: #c1cac128
            }

            .imbuto_text {
                margin-top: 50px;
                margin-left: 20px;
                padding-left: 50px;
            }
            #body-imbuto{
                margin-left:20px;
            }

            .imbuto-menu {
                /* margin-top: 63px; */
                margin-top: 90px;
            }

            .card {
                box-shadow: 15px 15px 8px 10px rgba(0, 0, 0, 0.2);
                /* this adds the "card" effect */
                padding: 6px;
                text-align: center;
                background-color: #f1f1f1;
                margin-top: 50px;
            }

            .form-inline{
                float: right;
            }
            .imbuto-colomun {
                border-radius: 50px;
                background-color: #333;
            }
            .d-block{
                height: 700px;
            }
            .ifumbile-style{
                /* background-color: rgba(53, 62, 78, 0.856); */
                background: rgba(130, 148, 241, 0.452);
                height:auto;
            }
            .columun-container{
                margin-top: 30px;
            }
            .ifumbire-picture{
                margin-top: 50px;
                width: 100%;
                height: 200px;
            }
            /* .imfumbire-center{
                background-color: #545f3769;
            }
            .column-imbire2{
                margin-top: 10px;
            } */
            .image-border{
                width: 100px;
                height: 100px;
             border-radius: 50%;
             margin-left: 150px;
             margin-top: 20px;
            }
            .ifumbire-image img{
                width: 100%;
                height: 300px;
                
            }  
            .border-image{
                width: 50%;
                height: 50%;
                border-radius: 50%;
            }
            .card-body .border-image{
               
                border-radius: 50%;
                text-align: center;
                display: block;
                 margin-left: auto;
                margin-right: auto;
                width: 50%;
            }
            #ifumbire-color{
                background-color:  #011A98;
                color:#f1f1f1;
            }
            .container h2{
               text-align: center;
               font-weight: 400; 
               color:rgba(46, 87, 63, 0.842); 
               
            }
            .card-imbure{
                width: 300px;
                height: 200px;
            }
            .imfumbire-column{
                margin-top: 20px;
            }
            .design-bground .card{
                color:black;
                }
                /* background-color: rgb(130, 148, 241); */
            /* .card-title{
                text-align: center;
                padding-top: 50px;
                padding-bottom:50px; 
            } */
            .contact-form{
                margin-top: 10px;
                padding-bottom: 10px;
                margin-bottom: 20px;

            }
            .contact-title {
                margin-top: 20px;
                padding-top: 20px;
                margin-bottom: 20px;
                color: #799038;
                font-size: 30px;
            }
            .btn-success{
                text-align: center;
                background-color: rgba(23, 126, 100, 0.801);
              
            }
            .card-img-top{
                width: 100%;
                height: 120px;
            }
            .imishwi_images{
                width: 100%;
                height: 150px;
            }
        </style>
        {% render_block "css" %}
    </head>

<body>
    {% cms_toolbar %}

    {% load menu_tags %}
    <section id="nav-bar">
            <nav class="navbar navbar-expand-lg">
            <div class="container">
                {% load static %}
                <a class="navbar-brand" href="/en">
                    <img src="{% static "../static/acg.jpeg" %}"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <i class="fa fa-bars"></i>
                    </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">

                    <ul class="navbar-nav">
                        <li class="nav-item">
                            {% show_menu 0 100 100 100 "menu.html"%}
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0 text-right">
                            <input class="form-control mr-sm-3" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                          </form>
                </div>
               
            </div>
        </nav>
        
    </section>
    {% block content %}
    {% endblock content %}

    <footer>
        {%  static_placeholder "footer" %}
    </footer>
    </div>
    {% render_block "js" %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

acg/templates/contact.html
{% extends "/base.html" %}


<html>

<body>


  <div class="col-md-4">
    {% block title %}Start a New Topic{% endblock %}

    {% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
    <li class="breadcrumb-item active">New topic</li>
    {% endblock %}
    {% block content %}
    <div class="container">
      <div class="row">

        <div class="col-md-3">
          <!-- {%load static%}
                                <img  src="{% static "../static/ifumbi.jpg" %}"> -->
        </div>
        <div class="col-md-6">
          <form action="" method="POST" class="contact-form">

            {% csrf_token %}
            <div class="form-group">

              <div class="contact-title">
                <h4"> Contact us here:</h4>
              </div>
              <label for="id_firstname"><b>Name</b></label>
              <input type="text" class="form-control" id="id_subject" name="firstname">
            </div>
            <div class="form-group">
              <label for="id_email"><b>Email</b></label>
              <input type="email" class="form-control" id="id_email" name="email">
            </div>
            <div class="form-group">
              <label for="id_message"><b>Message</b></label>
              <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
            </div>
            <button type="submit" class="btn btn-success">Send Message</button>
          </form>
        </div>
        <div class="col-md-3">
          <!-- {%load static%}
                                    <img  src="{% static "../static/ifumbi.jpg" %}"> -->
        </div>


      </div>
    </div>
    <p></p>
    {% endblock %}
</body>

</html>


<footer>
  {% include "footer_word.html" %}
</footer>

acg/templates/default.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
<!-- The start of the upper part containing slide and pub part -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            {% load static %}
            <img class="d-block w-100 " src="{% static "../static/chicago.jpg" %}" alt="First slide"
                style="height: 400px;">
        </div>
        <div class="carousel-item">
            {% load static %}
            <img class="d-block w-100 " src="{% static "../static/ny.jpg" %}" alt="Second slide"
                style="height: 400px;">
        </div>
        <div class="carousel-item">
            {% load static %}
            <img class="d-block w-100" src="{% static "../static/la.jpg" %}" alt="Third slide"
                style="height: 400px;">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<!-- The end of the upper part containing slide and pub part -->
<div class="container-fluid main-body">

  <!-- beginning of row div-->
  <div class="row">

    <div class="col-sm-1"></div>

    <div class="col-sm-2">
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="col">
            <input type="text" class="form-control" placeholder="Search">
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <ul class="nav flex-column">
            <li class="nav-item active">
              <a class="nav-link " href="{% url 'imbuto' %}">Imbuto</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'imishwi' %}">Imishwi</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ifumbire' %}">Ifumbire</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>

    <div class="col-sm-7">
      <div class="album py-5">
        <div class="container">
          <div class="row">
            {% placeholder "one-product" %}
          </div>
        </div>
      </div>
    </div>

  </div>
  <!-- end of row div -->
</div>

<!-- the start of the content of the display about products -->
{% endblock content %}
<footer>
  {% include "footer_word.html" %}
</footer>

acg/templates/footer_word.html
{% extends "base.html" %}
{% load cms_tags %}
<footer class="footer-word">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <footer style="background-color: cadetblue; color:white;">                
                    {% static_placeholder "footer" %}
                </footer>

            </div>
        </div>
    </div>
</footer>

acg/templates/fullwidth.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
	{% placeholder "content" %}
{% endblock content %}

acg/templates/menu.html
{% for child in children %}
<!-- no child pages  -->
{% if child.is_leaf_node %}
<li
    class="nav-item {% if 'blog' in request.path and child.get_menu_title == 'BLOG' %} active {% endif %} {% if child.selected %} active {% endif %}">
    <a href="{{ child.get_absolute_url }}" class="nav-link">{{child.get_menu_title }}</a></li>
{% endif %}
<!-- /no child pages  -->
<!-- has child pages  -->
{% if not child.is_leaf_node or child.ancestor %}
<li class="nav-item ml-4 dropdown {% if child.ancestor %} active {% endif %}">
    <a class="nav-link dropdown-toggle w3-bar-item" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false" href="#">
        {{child.get_menu_title }}
    </a>
    <div class="dropdown-menu sub-menu-dropdown border-0 dropdown-content" aria-labelledby="navbarDropdown">
        {% if child.get_descendants %}
        {% for kid in child.get_descendants %}
        <a class="second-menu dropdown-item" href="{{ kid.get_absolute_url }}">
            {{kid.get_menu_title }}
        </a>
        {% endfor %}
        {% endif %}
    </div>
</li>
{% endif %}
<!-- /has child pages  -->
{% endfor %}
<!-- /end for child -->

acg/templates/sidebar_left.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
    <div class="content">
        {% placeholder "content" %}
    </div>
{% endblock content %}

acg/templates/sidebar_right.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="content">
        {% placeholder "content" %}
    </div>
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
{% endblock content %}

acg/templates/slide.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
{% placeholder "content" %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                {% load static %}
                <img class="d-block w-500 " src="{% static "../static/chicago.jpg" %}" alt="First slide"
                    style="height: 100px;">
            </div>
            <div class="carousel-item">
                {% load static %}
                <img class="d-block w-500 " src="{% static "../static/ny.jpg" %}" alt="Second slide"
                    style="height: 100px;">
            </div>
            <div class="carousel-item">
                {% load static %}
                <img class="d-block w-500" src="{% static "../static/la.jpg" %}" alt="Third slide"
                    style="height: 500px;">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
{% endblock content %}